import path from 'node:path';
import type { Finding, Severity } from '../core/types.js';

export type GitHubFindingState = 'untracked' | 'new' | 'persistent' | 'resolved';
export type GitHubPlannedAction = 'review' | 'create' | 'keep-open' | 'resolve';

export interface GitHubIssueDraft {
  title: string;
  body: string;
  labels: string[];
}

export interface GitHubIssuePlanEntry {
  fingerprint: string;
  state: GitHubFindingState;
  action: GitHubPlannedAction;
  severity: Severity;
  kind: string;
  issue?: GitHubIssueDraft;
}

export interface GitHubIssuePlanDocument {
  version: 1;
  runId: string;
  generatedAt: string;
  memoryExisted: boolean;
  entries: GitHubIssuePlanEntry[];
}

const SECRET_ASSIGNMENT = /\b(password|passwd|token|api[-_]?key|secret|authorization|cookie|session|credential)\s*[:=]\s*([^\s,;]+)/gi;
const BEARER = /\bBearer\s+[A-Za-z0-9._~+/=-]+/gi;
const EMAIL = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi;

function bounded(value: string, max: number): string {
  const normalized = value.replace(/\r\n/g, '\n').replace(/\u0000/g, '').trim();
  return normalized.length <= max ? normalized : `${normalized.slice(0, Math.max(0, max - 1))}…`;
}

export function redactIssueText(value: string): string {
  return bounded(value, 4_000)
    .replace(BEARER, 'Bearer [REDACTED]')
    .replace(SECRET_ASSIGNMENT, (_match, key: string) => `${key}=[REDACTED]`)
    .replace(EMAIL, '[REDACTED_EMAIL]');
}

export function safeIssueUrl(value: string): string {
  try {
    const url = new URL(value);
    if (url.protocol === 'device:') return `${url.protocol}//${url.hostname || 'unknown'}`;
    url.username = '';
    url.password = '';
    url.search = '';
    url.hash = '';
    return bounded(url.toString(), 1_000);
  } catch {
    return '[invalid-url]';
  }
}

function safeEvidence(value: string): string {
  const normalized = value.replace(/\\/g, '/');
  const screenshotIndex = normalized.lastIndexOf('/screenshots/');
  if (screenshotIndex >= 0) return bounded(normalized.slice(screenshotIndex + 1), 500);
  return bounded(path.basename(normalized), 500);
}

function severityRank(value: Severity): number {
  return ({ critical: 5, high: 4, medium: 3, low: 2, info: 1 })[value];
}

function labelsFor(finding: Finding): string[] {
  return [
    'ai-qa',
    `severity:${finding.severity}`,
    `kind:${finding.kind}`,
  ].map((value) => bounded(value.toLowerCase().replace(/[^a-z0-9:._-]+/g, '-'), 50));
}

export function buildIssueDraft(finding: Finding): GitHubIssueDraft {
  const reproduction = finding.reproduction
    .slice(0, 12)
    .map((step, index) => `${index + 1}. ${redactIssueText(bounded(step, 800))}`)
    .join('\n');
  const evidence = finding.evidence
    .slice(0, 12)
    .map((item) => `- \`${safeEvidence(item)}\``)
    .join('\n');

  const title = bounded(`[AI QA][${finding.severity.toUpperCase()}] ${redactIssueText(finding.title)}`, 140);
  const body = bounded([
    '## AI QA finding',
    '',
    `**Severity:** ${finding.severity}`,
    `**Kind:** ${finding.kind}`,
    `**Fingerprint:** \`${finding.fingerprint}\``,
    `**URL:** ${safeIssueUrl(finding.url)}`,
    '',
    '### Observation',
    redactIssueText(finding.message),
    '',
    '### Reproduction',
    reproduction || '1. Re-run the recorded QA scenario.',
    '',
    '### Evidence',
    evidence || '- See the run event/evidence bundle for this fingerprint.',
    '',
    '> Generated by AI QA Operating System. Review before publishing or changing repository state.',
  ].join('\n'), 12_000);

  return { title, body, labels: labelsFor(finding) };
}

export function buildGitHubIssuePlan(
  runId: string,
  findings: Finding[],
  priorFingerprints: Map<string, { severity: Severity; kind: string; title: string }>,
  memoryExisted: boolean,
): GitHubIssuePlanDocument {
  const current = new Map(findings.map((finding) => [finding.fingerprint, finding]));
  const entries: GitHubIssuePlanEntry[] = [];

  for (const finding of findings) {
    const state: GitHubFindingState = !memoryExisted
      ? 'untracked'
      : priorFingerprints.has(finding.fingerprint)
        ? 'persistent'
        : 'new';
    entries.push({
      fingerprint: finding.fingerprint,
      state,
      action: state === 'untracked' ? 'review' : state === 'new' ? 'create' : 'keep-open',
      severity: finding.severity,
      kind: finding.kind,
      issue: buildIssueDraft(finding),
    });
  }

  if (memoryExisted) {
    for (const [fingerprint, prior] of priorFingerprints) {
      if (current.has(fingerprint)) continue;
      entries.push({
        fingerprint,
        state: 'resolved',
        action: 'resolve',
        severity: prior.severity,
        kind: prior.kind,
      });
    }
  }

  entries.sort((a, b) => {
    const actionRank = ({ create: 4, review: 3, 'keep-open': 2, resolve: 1 }) as Record<GitHubPlannedAction, number>;
    return actionRank[b.action] - actionRank[a.action]
      || severityRank(b.severity) - severityRank(a.severity)
      || a.fingerprint.localeCompare(b.fingerprint);
  });

  return {
    version: 1,
    runId,
    generatedAt: new Date().toISOString(),
    memoryExisted,
    entries,
  };
}
