export function beta8DashboardJs(): string {
  return `(()=>{
'use strict';
let state=null,pending=false;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function zh(){return (document.documentElement.lang||'').toLowerCase()==='zh-tw'}
function L(en,tc){return zh()?tc:en}
function answerMap(data){return new Map((((data||{}).interview||{}).answers||[]).map(a=>[a.questionId,a]))}
function statusLabel(v){const map={planned:['Planned','已規劃'],approved:['Approved','已核准'],'in-progress':['Running','執行中'],blocked:['Blocked','受阻'],verification:['Verification','驗證中'],completed:['Completed','已完成'],'proposal-ready':['Proposal ready','方案待審閱'],planning:['Planning','產生方案中'],executing:['Executing','執行中'],error:['Error','錯誤']};return map[v]?L(map[v][0],map[v][1]):String(v||'—')}
function valueControl(q,a){const value=a?a.value:null;
  if(q.kind==='boolean')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option><option value="true" '+(value===true?'selected':'')+'>'+esc(L('Yes','是'))+'</option><option value="false" '+(value===false?'selected':'')+'>'+esc(L('No','否'))+'</option></select>';
  if(q.kind==='single')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option>'+((q.options||[]).map(o=>'<option value="'+esc(o)+'" '+(value===o?'selected':'')+'>'+esc(o)+'</option>').join(''))+'</select>';
  if(q.kind==='multi'){const selected=new Set(Array.isArray(value)?value:[]);return '<div class="b8-choice-grid">'+(q.options||[]).map(o=>'<label><input type="checkbox" data-b8-multi="'+esc(q.id)+'" value="'+esc(o)+'" '+(selected.has(o)?'checked':'')+'><span>'+esc(o)+'</span></label>').join('')+'</div>'}
  return '<textarea data-b8-input="'+esc(q.id)+'" rows="3" placeholder="'+esc(L('Enter details','輸入內容'))+'">'+esc(typeof value==='string'?value:'')+'</textarea>';
}
function questionCard(q,a,actionsAllowed){const suggested=(q.suggested||[]).length?'<small>'+esc(L('Suggested: ','建議：'))+esc(q.suggested.join(', '))+'</small>':'';const badge=q.requiresExplicitConfirmation?'<span class="chip">'+esc(L('Explicit confirmation','需明確確認'))+'</span>':'';return '<article class="panel b8-question" data-b8-question="'+esc(q.id)+'"><div class="card-heading"><div><h2>'+esc(q.prompt)+'</h2><small>'+esc(q.rationale)+'</small></div>'+badge+'</div>'+suggested+'<div class="b8-answer">'+valueControl(q,a)+'</div><div class="pipeline-toolbar"><span class="chip">'+esc(a&&a.confirmed?L('Confirmed','已確認'):L('Not confirmed','未確認'))+'</span><button class="primary-button" data-b8-save="'+esc(q.id)+'" '+(!actionsAllowed||pending?'disabled':'')+'>'+esc(L('Save & confirm','儲存並確認'))+'</button></div></article>'}
function dependenciesReady(item,items){const byId=new Map((items||[]).map(i=>[i.id,i]));return (item.dependencies||[]).every(id=>byId.get(id)&&byId.get(id).status==='completed')}
function defaultScope(item){if(item.kind==='frontend')return 'src/**';if(item.kind==='qa')return '';return 'backend/**'}
function proposalDetails(action){const p=action&&action.latestProposal&&action.latestProposal.summary;if(!p)return '';const changes=(p.changes||[]).map(c=>'<li><strong>'+esc(c.operation)+'</strong> '+esc(c.path)+'</li>').join('');const tests=(p.targetedTests||[]).map(v=>'<li>'+esc(v)+'</li>').join('');return '<div class="b8-proposal"><div class="decision-grid"><div><b>'+esc(L('Proposal hash','方案雜湊'))+'</b><span class="b8-hash">'+esc(p.proposalHash)+'</span></div><div><b>'+esc(L('Scope hash','範圍雜湊'))+'</b><span class="b8-hash">'+esc(p.scopeHash)+'</span></div><div><b>'+esc(L('Changes','修改檔案'))+'</b><span>'+esc((p.changes||[]).length)+'</span></div><div><b>'+esc(L('Beta.7 gate','Beta.7 Gate'))+'</b><span>'+esc(p.beta7Qa||L('Required but proposal omitted command','需要，但方案未提供命令'))+'</span></div></div><p>'+esc(p.summary||'')+'</p><div class="decision-grid"><div><b>'+esc(L('Exact reviewed changes','精確修改範圍'))+'</b><ul>'+changes+'</ul></div><div><b>'+esc(L('Targeted tests','目標測試'))+'</b><ul>'+tests+'</ul></div><div><b>'+esc(L('Regression','回歸測試'))+'</b><span>'+esc(p.regression||'—')+'</span></div><div><b>'+esc(L('Source content','程式碼內容'))+'</b><span>'+esc(L('Not exposed in dashboard summary','不在管理面板摘要暴露'))+'</span></div></div></div>'}
function taskCard(item,items,data){const action=item.action||{};const phase=action.phase||item.status;const ready=dependenciesReady(item,items);let controls='';
  if(item.kind==='qa'){controls='<span class="chip">'+esc(L('Verification-only task; executed by the Beta.7 gate workflow','僅驗證任務；由 Beta.7 Gate 流程執行'))+'</span>'}
  else if(item.status==='planned'&&!item.approved){controls=ready?'<div class="b8-task-form"><label><span>'+esc(L('Approver','核准者'))+'</span><input data-b8-approver="'+esc(item.id)+'" value="owner" maxlength="120"></label><label><span>'+esc(L('Allowed repository paths','允許的 Repository 路徑'))+'</span><input data-b8-scope="'+esc(item.id)+'" value="'+esc(defaultScope(item))+'" placeholder="backend/**" maxlength="2000"></label><button class="primary-button" data-b8-task-action="approve" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Approve bounded scope','核准受控範圍'))+'</button></div>':'<span class="chip">'+esc(L('Waiting for dependencies','等待前置任務'))+'</span>'}
  else if(item.status==='approved'&&!action.latestProposal){controls=data.configuration.model?'<button class="primary-button" data-b8-task-action="propose" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Generate implementation proposal','產生實作方案'))+'</button>':'<span class="chip">'+esc(L('Configure Beta.8 model endpoint','請設定 Beta.8 模型端點'))+'</span>'}
  else if(item.status==='approved'&&action.latestProposal){const p=action.latestProposal.summary;const tail=p.proposalHash.slice(-8);controls='<div class="b8-task-form"><label><span>'+esc(L('Type proposal hash suffix to execute','輸入方案雜湊末 8 碼後執行'))+' · <b>'+esc(tail)+'</b></span><input data-b8-confirm="'+esc(item.id)+'" maxlength="8" placeholder="'+esc(tail)+'"></label><button class="primary-button" data-b8-task-action="execute" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Execute reviewed task','執行已審閱任務'))+'</button></div>'}
  else if(item.status==='completed')controls='<span class="chip">'+esc(L('Verified; local changes await review/commit before the next clean-workspace task','已驗證；本機變更需審閱/commit 後才能執行下一個 clean-workspace 任務'))+'</span>'
  else controls='<span class="chip">'+esc(statusLabel(phase))+'</span>';
  return '<section class="panel b8-task"><div class="card-heading"><div><h2>'+esc(item.title)+'</h2><small>'+esc(item.id)+' · '+esc(item.kind)+' · '+esc(item.priority)+'</small></div><span class="status-pill '+esc(item.status)+'">'+esc(statusLabel(phase))+'</span></div><p>'+esc(action.message||'')+'</p><div class="decision-grid"><div><b>'+esc(L('Dependencies','依賴'))+'</b><span>'+esc((item.dependencies||[]).join(', ')||'—')+'</span></div><div><b>'+esc(L('Approved','已核准'))+'</b><span>'+esc(item.approved?L('Yes','是'):L('No','否'))+'</span></div><div><b>'+esc(L('Allowed paths','允許路徑'))+'</b><span>'+esc((item.allowedPaths||[]).join(', ')||'—')+'</span></div><div><b>'+esc(L('Attempt','嘗試'))+'</b><span>'+esc(action.latestAttempt?action.latestAttempt.outcome:'—')+'</span></div></div>'+proposalDetails(action)+'<div class="pipeline-toolbar">'+controls+'</div></section>'}
function render(data){state=data;const page=document.querySelector('[data-page="beta8"]');if(!page)return;let host=document.getElementById('beta8LiveWorkflow');if(!host){host=document.createElement('div');host.id='beta8LiveWorkflow';page.appendChild(host)}
  if(data.error){host.innerHTML='<article id="beta8Error" class="panel">'+esc(data.error)+'</article>';return}
  if(data.phase==='not-started'){const can=data.configuration.repo&&data.actionsAllowed&&!pending;host.innerHTML='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend discovery','前端地毯式盤點'))+'</h2><small>'+esc(L('Read the existing frontend first. No backend code is generated in this step.','先完整讀取現有前端；此步驟不會產生後端程式碼。'))+'</small></div><span class="chip">Beta.8</span></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Discover" '+(can?'':'disabled')+'>'+esc(!data.configuration.repo?L('Configure repository first','請先設定 Repository'):!data.actionsAllowed?L('Read-only mode','唯讀模式'):L('Scan frontend','掃描前端'))+'</button></div></article>';const b=document.getElementById('b8Discover');if(b&&can)b.addEventListener('click',discover);return}
  const d=data.discovery||{};let html='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend inventory','前端盤點結果'))+'</h2><small>'+esc(d.projectName||'')+'</small></div><span class="chip">'+esc(data.phase)+'</span></div><div class="decision-grid"><div><b>'+esc(L('Files scanned','掃描檔案'))+'</b><span>'+esc(d.filesScanned||0)+'</span></div><div><b>'+esc(L('Routes / Forms','路由 / 表單'))+'</b><span>'+esc((d.routes||0)+' / '+(d.forms||0))+'</span></div><div><b>'+esc(L('API candidates','API 候選'))+'</b><span>'+esc(d.apiCandidates||0)+'</span></div><div><b>'+esc(L('Mock sources','Mock 來源'))+'</b><span>'+esc(d.mockSources||0)+'</span></div></div><p>'+esc(L('Frameworks: ','框架：'))+esc((d.frameworks||[]).join(', ')||'—')+'</p><p>'+esc(L('Entities: ','實體：'))+esc((d.entities||[]).join(', ')||'—')+'</p></article>';
  if(data.interview&&!data.blueprint){const answers=answerMap(data);const v=data.interview.validation||{};html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Architecture interview','後端架構訪談'))+'</h2><small>'+esc(L('Every required architecture decision must be explicitly confirmed before generation.','所有必要架構決策都必須明確確認後，才可開始生成。'))+'</small></div><span class="chip">'+esc(v.readyForBlueprint?L('Ready','可產生 Blueprint'):L('Blocked','尚未完成'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Missing','未回答'))+'</b><span>'+esc((v.missing||[]).length)+'</span></div><div><b>'+esc(L('Unconfirmed','未確認'))+'</b><span>'+esc((v.unconfirmed||[]).length)+'</span></div><div><b>'+esc(L('Invalid','無效'))+'</b><span>'+esc((v.invalid||[]).length)+'</span></div><div><b>'+esc(L('Unknown / duplicate','未知 / 重複'))+'</b><span>'+esc((v.unknownQuestionIds||[]).length+(v.duplicateQuestionIds||[]).length)+'</span></div></div></article>';
    for(const round of data.interview.rounds||[]){html+='<section class="b8-round"><div class="page-heading"><div><div class="eyebrow">'+esc(round.id)+'</div><h1>'+esc(round.title)+'</h1></div></div>'+round.questions.map(q=>questionCard(q,answers.get(q.id),data.actionsAllowed)).join('')+'</section>'}
    if(v.readyForBlueprint)html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Generate security-first blueprint','產生資安優先 Blueprint'))+'</h2><small>'+esc(L('This creates architecture, Work Plan and Mock Migration Plan artifacts. It still does not mutate product source code.','此動作會建立架構、Work Plan 與 Mock Migration Plan；仍不會修改產品程式碼。'))+'</small></div></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Blueprint" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Generate blueprint','產生 Blueprint'))+'</button></div></article>';
  }
  if(data.blueprint){const b=data.blueprint;html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Backend blueprint ready','後端 Blueprint 已完成'))+'</h2><small>'+esc(b.architecture.backendLanguage+' · '+b.architecture.backendFramework+' · '+b.architecture.database)+'</small></div><span class="chip">'+esc(b.workPlanValid?L('Work Plan valid','Work Plan 有效'):L('Work Plan blocked','Work Plan 受阻'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Security controls','資安控制'))+'</b><span>'+esc(b.securityControls)+'</span></div><div><b>'+esc(L('Threat surfaces','威脅面'))+'</b><span>'+esc(b.threatSurface)+'</span></div><div><b>'+esc(L('API / Entities','API / 實體'))+'</b><span>'+esc(b.apiEndpoints+' / '+b.entities)+'</span></div><div><b>'+esc(L('Tasks / Mocks','任務 / Mocks'))+'</b><span>'+esc(b.tasks+' / '+b.mockMigrationItems)+'</span></div></div></article><section class="b8-task-stack"><div class="page-heading"><div><div class="eyebrow">Beta.8 Implementation</div><h1>'+esc(L('Governed task execution','受控任務執行'))+'</h1><p>'+esc(L('Approve scope → generate proposal → review exact files/tests/hash → confirm execution. Source contents remain server-side.','核准範圍 → 產生方案 → 審閱精確檔案/測試/雜湊 → 確認執行。程式碼內容保留在伺服器端。'))+'</p></div></div>'+(b.workItems||[]).map(i=>taskCard(i,b.workItems,data)).join('')+'</section>'}
  host.innerHTML=html;host.querySelectorAll('[data-b8-save]').forEach(el=>el.addEventListener('click',()=>saveAnswer(el.getAttribute('data-b8-save'))));host.querySelectorAll('[data-b8-task-action]').forEach(el=>el.addEventListener('click',()=>taskAction(el.getAttribute('data-b8-task-action'),el.getAttribute('data-b8-item'))));const bp=document.getElementById('b8Blueprint');if(bp&&data.actionsAllowed)bp.addEventListener('click',generateBlueprint)
}
async function post(endpoint,payload){if(!state||!state.actionsAllowed)throw new Error(L('Dashboard is read-only.','管理面板目前為唯讀。'));const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body}
async function refresh(){try{const r=await fetch('/api/beta8',{headers:{accept:'application/json'},cache:'no-store'});render(await r.json())}catch(e){console.error('beta8 dashboard refresh failed',e)}}
async function discover(){if(pending)return;pending=true;try{render(state);render(await post('/api/beta8/discover',{}))}catch(e){showError(e)}finally{pending=false}}
function readQuestionValue(id,q){if(q.kind==='multi')return Array.from(document.querySelectorAll('[data-b8-multi="'+CSS.escape(id)+'"]:checked')).map(el=>el.value);const el=document.querySelector('[data-b8-input="'+CSS.escape(id)+'"]');if(!el)return '';if(q.kind==='boolean')return el.value==='true'?true:el.value==='false'?false:'';return el.value}
function showError(e){let host=document.getElementById('beta8Error');if(!host){host=document.createElement('div');host.id='beta8Error';host.className='panel';document.getElementById('beta8LiveWorkflow')?.prepend(host)}host.textContent=String(e&&e.message||e)}
async function saveAnswer(id){if(pending||!state||!state.interview)return;const q=(state.interview.rounds||[]).flatMap(r=>r.questions).find(x=>x.id===id);if(!q)return;const value=readQuestionValue(id,q);pending=true;try{render(await post('/api/beta8/answer',{questionId:id,value,confirmed:true}))}catch(e){showError(e)}finally{pending=false}}
async function generateBlueprint(){if(pending)return;pending=true;try{render(await post('/api/beta8/blueprint',{}))}catch(e){showError(e)}finally{pending=false}}
async function taskAction(action,itemId){if(pending||!itemId||!state||!state.blueprint)return;const item=state.blueprint.workItems.find(i=>i.id===itemId);if(!item)return;pending=true;try{
  if(action==='approve'){const who=document.querySelector('[data-b8-approver="'+CSS.escape(itemId)+'"]')?.value.trim();const raw=document.querySelector('[data-b8-scope="'+CSS.escape(itemId)+'"]')?.value||'';const allowedPaths=raw.split(/[\n,]+/).map(v=>v.trim()).filter(Boolean);render(await post('/api/beta8/approve-task',{itemId,approvedBy:who,allowedPaths}))}
  else if(action==='propose')render(await post('/api/beta8/propose-task',{itemId}));
  else if(action==='execute'){const p=item.action&&item.action.latestProposal&&item.action.latestProposal.summary;if(!p)throw new Error(L('No reviewed proposal is available.','沒有可審閱的方案。'));const typed=document.querySelector('[data-b8-confirm="'+CSS.escape(itemId)+'"]')?.value.trim();if(typed!==p.proposalHash.slice(-8))throw new Error(L('Proposal hash confirmation does not match; no files were changed.','方案雜湊確認碼不符，未修改任何檔案。'));render(await post('/api/beta8/execute-task',{itemId,proposalHash:p.proposalHash,confirmWrite:true}))}
}catch(e){showError(e)}finally{pending=false}}
function rerender(){if(state)render(state)}
function start(){refresh();setInterval(refresh,7000);new MutationObserver(rerender).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();`;
}
