export function beta9DashboardCss(): string {
  return `
.beta9-dialog-backdrop{position:fixed;inset:0;z-index:1000;background:color-mix(in srgb,var(--bg,#0d1117) 72%,transparent);backdrop-filter:blur(12px);display:grid;place-items:center;padding:24px}
.beta9-dialog{width:min(720px,100%);max-height:min(84vh,820px);overflow:auto;border:1px solid var(--border,#273246);border-radius:22px;background:var(--panel,#151b27);box-shadow:0 28px 80px rgba(0,0,0,.36);padding:24px}
.beta9-dialog-header{display:flex;align-items:flex-start;gap:16px;margin-bottom:18px}.beta9-dialog-icon{display:grid;place-items:center;flex:0 0 44px;height:44px;border-radius:14px;background:color-mix(in srgb,#7c5cff 18%,transparent);color:#9f8cff;font-size:20px}.beta9-dialog-header h2{margin:0 0 6px;font-size:20px}.beta9-dialog-header p{margin:0;color:var(--muted,#8994a8);line-height:1.55}.beta9-dialog-close{margin-left:auto;border:0;background:transparent;color:inherit;font-size:22px;cursor:pointer;padding:4px 8px;border-radius:10px}.beta9-dialog-close:hover{background:color-mix(in srgb,currentColor 8%,transparent)}
.beta9-dialog-body{display:grid;gap:16px}.beta9-dialog-callout{border:1px solid var(--border,#273246);border-radius:16px;padding:14px 16px;background:color-mix(in srgb,var(--panel,#151b27) 82%,#7c5cff 18%)}.beta9-dialog-callout strong,.beta9-dialog-callout code{display:block;overflow-wrap:anywhere}.beta9-dialog-callout small{display:block;margin-top:6px;color:var(--muted,#8994a8);line-height:1.5}
.beta9-dialog-field{display:grid;gap:8px}.beta9-dialog-field span{font-size:13px;font-weight:700}.beta9-dialog-field input{width:100%;box-sizing:border-box;border:1px solid var(--border,#273246);background:var(--surface,#0f1520);color:inherit;border-radius:12px;padding:12px 14px;font:inherit;outline:none}.beta9-dialog-field input:focus{border-color:#7c5cff;box-shadow:0 0 0 3px color-mix(in srgb,#7c5cff 20%,transparent)}
.beta9-dialog-list{margin:0;padding-left:20px;color:var(--muted,#8994a8);line-height:1.6}.beta9-dialog-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px;flex-wrap:wrap}.beta9-dialog-actions button{min-width:110px}.beta9-dialog-danger{color:#ff8b8b}.beta9-dialog-success{color:#65d6a4}.beta9-dialog-hash{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;letter-spacing:.03em}
body.beta9-dialog-open{overflow:hidden}
@media(max-width:700px){.beta9-dialog-backdrop{padding:12px;align-items:end}.beta9-dialog{border-radius:20px 20px 12px 12px;padding:18px;max-height:90vh}.beta9-dialog-header{gap:12px}.beta9-dialog-actions{display:grid;grid-template-columns:1fr 1fr}.beta9-dialog-actions button{width:100%;min-width:0}}
`;
}
