export function beta8DashboardJs(): string {
  return `(()=>{
'use strict';
let state=null,pending=false;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function zh(){return (document.documentElement.lang||'').toLowerCase()==='zh-tw'}
function L(en,tc){return zh()?tc:en}
const ROUND_ZH={
  'project-understanding':'確認產品邊界','backend-stack':'選擇後端技術棧','data-auth':'資料與身分驗證','security-operations':'資安與營運策略','mock-release':'Mock 遷移與發佈策略'
};
const QUESTION_ZH={
  'product-boundary':['此次後端生成應涵蓋哪一個產品範圍？','地毯式盤點可能發現多個功能區；請先確認要轉成真實後端的邊界。'],
  'discovery-limit':['若盤點因檔案上限而不完整，是否先停止並擴大盤點？','不能在證據不完整時假設已理解整個前端。'],
  'backend-language':['後端要使用哪一種語言／Runtime？','AI 可以提出候選，但技術棧必須由使用者明確決定。'],
  'backend-framework':['要使用哪一個後端框架？','框架會影響路由、驗證、中介層、測試與部署方式。'],
  'deployment-target':['後端預計部署在哪裡？','部署環境會影響 Runtime、Secret、Storage、網路與觀測性設計。'],
  'database-strategy':['要使用哪一種資料庫策略？','資料模型、交易、一致性與遷移方式都依此決定。'],
  'authentication-strategy':['身分驗證要採用哪一種方式？','登入/session/token 邊界必須在產生程式碼前確認。'],
  'authorization-strategy':['授權模型要採用哪一種方式？','後端預設採 deny-by-default，但仍需確認角色與權限模型。'],
  'data-classification':['系統會處理哪些資料敏感等級？','資料分類會直接影響加密、日誌、保存與存取控制。'],
  'security-baseline':['是否接受必要的最低資安基線？','輸入驗證、授權、Rate limit、Secret isolation、安全錯誤與稽核不得為了開發方便被移除。'],
  'external-capabilities':['需要哪些外部能力？','檔案儲存、Realtime、Queue、Cache、Email 或第三方服務會擴大攻擊面。'],
  'mock-strategy':['現有 Mock 資料要如何處理？','每個 Mock 來源都必須明確決定保留、接真實 API、轉 Seed 或驗證後移除。'],
  'seed-policy':['哪些 Mock 可以轉成真實後端的示範／Seed 資料？','演示資料也可能包含敏感內容，因此不能自動整批搬移。'],
  'beta7-gate':['每個階段完成後是否執行 Beta.7 QA Gate？','階段性驗證能避免錯誤一路累積到整個後端完成後才發現。']
};
const OPTION_ZH={
  'Keep current discovered boundary':'維持目前盤點出的產品邊界','Narrow to selected modules':'縮小到指定模組','Expand after another discovery pass':'先再次完整盤點再擴大範圍',
  'Yes - stop and expand discovery':'是，停止並擴大盤點','No - continue with explicit incomplete scope':'否，以明確標示的不完整範圍繼續',
  'Other':'其他','None / in-memory only':'不使用／僅記憶體','Managed SQL service':'託管式 SQL 服務','Managed NoSQL service':'託管式 NoSQL 服務',
  'Session cookies':'Session Cookie','JWT access/refresh tokens':'JWT Access/Refresh Token','OAuth/OIDC provider':'OAuth/OIDC Provider','Passkeys/WebAuthn':'Passkeys/WebAuthn','No authentication':'不需要登入',
  'Role-based (RBAC)':'角色式權限（RBAC）','Attribute/policy-based':'屬性／政策式權限','Resource ownership + roles':'資源擁有者＋角色','Single-user/no authorization':'單一使用者／不需要授權',
  'Public only':'僅公開資料','Internal/non-sensitive':'內部但非敏感資料','Personal data':'個人資料','Credentials/tokens':'憑證／Token','Financial/payment':'金融／付款資料','Health/highly sensitive':'健康／高度敏感資料',
  'Accept mandatory baseline':'接受必要最低資安基線','Need stricter controls':'需要更嚴格的控制',
  'File/object storage':'檔案／物件儲存','Realtime/WebSocket':'Realtime/WebSocket','Background jobs/queue':'背景工作／Queue','Cache':'Cache','Email/SMS':'Email/SMS','Third-party APIs':'第三方 API','None':'無',
  'Keep mocks temporarily':'暫時保留 Mock','Migrate approved mocks to seed/demo data':'將核准的 Mock 轉成 Seed／Demo 資料','Remove mocks after live backend verification':'真實後端驗證後移除 Mock','Mixed per-source decisions':'逐來源分別決定',
  'No automatic seed migration':'不自動轉移 Seed','Ask for each mock source':'每個 Mock 來源逐一詢問','Migrate all non-sensitive demo records':'轉移所有非敏感示範資料',
  'Required after every implementation stage':'每個實作階段都必須執行','Required before mock cleanup and final handoff':'Mock 清理與最終交付前必須執行'
};
function roundTitle(round){return zh()?(ROUND_ZH[round.id]||round.title):round.title}
function qText(q,index){const pair=QUESTION_ZH[q.id];return zh()&&pair?pair[index]:index===0?q.prompt:q.rationale}
function optionLabel(v){return zh()?(OPTION_ZH[v]||v):v}
function answerMap(data){return new Map((((data||{}).interview||{}).answers||[]).map(a=>[a.questionId,a]))}
function statusLabel(v){const map={planned:['Planned','已規劃'],approved:['Approved','已核准'],'in-progress':['Running','執行中'],blocked:['Blocked','受阻'],verification:['Verification','驗證中'],completed:['Completed','已完成'],'proposal-ready':['Proposal ready','方案待審閱'],planning:['Planning','產生方案中'],executing:['Executing','執行中'],error:['Error','錯誤']};return map[v]?L(map[v][0],map[v][1]):String(v||'—')}
function valueControl(q,a){const value=a?a.value:null;
  if(q.kind==='boolean')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option><option value="true" '+(value===true?'selected':'')+'>'+esc(L('Yes','是'))+'</option><option value="false" '+(value===false?'selected':'')+'>'+esc(L('No','否'))+'</option></select>';
  if(q.kind==='single')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option>'+((q.options||[]).map(o=>'<option value="'+esc(o)+'" '+(value===o?'selected':'')+'>'+esc(optionLabel(o))+'</option>').join(''))+'</select>';
  if(q.kind==='multi'){const selected=new Set(Array.isArray(value)?value:[]);return '<div class="b8-choice-grid">'+(q.options||[]).map(o=>'<label><input type="checkbox" data-b8-multi="'+esc(q.id)+'" value="'+esc(o)+'" '+(selected.has(o)?'checked':'')+'><span>'+esc(optionLabel(o))+'</span></label>').join('')+'</div>'}
  return '<textarea data-b8-input="'+esc(q.id)+'" rows="3" placeholder="'+esc(L('Enter details','輸入內容'))+'">'+esc(typeof value==='string'?value:'')+'</textarea>';
}
function questionCard(q,a,actionsAllowed){const suggested=(q.suggested||[]).length?'<small>'+esc(L('Suggested: ','建議：'))+esc(q.suggested.map(optionLabel).join(', '))+'</small>':'';const badge=q.requiresExplicitConfirmation?'<span class="chip">'+esc(L('Explicit confirmation','需明確確認'))+'</span>':'';return '<article class="panel b8-question" data-b8-question="'+esc(q.id)+'"><div class="card-heading"><div><h2>'+esc(qText(q,0))+'</h2><small>'+esc(qText(q,1))+'</small></div>'+badge+'</div>'+suggested+'<div class="b8-answer">'+valueControl(q,a)+'</div><div class="pipeline-toolbar"><span class="chip">'+esc(a&&a.confirmed?L('Confirmed','已確認'):L('Not confirmed','未確認'))+'</span><button class="primary-button" data-b8-save="'+esc(q.id)+'" '+(!actionsAllowed||pending?'disabled':'')+'>'+esc(L('Save & confirm','儲存並確認'))+'</button></div></article>'}
function dependenciesReady(item,items){const byId=new Map((items||[]).map(i=>[i.id,i]));return (item.dependencies||[]).every(id=>byId.get(id)&&byId.get(id).status==='completed')}
function defaultScope(item){if(item.kind==='frontend')return 'src/**';if(item.kind==='qa')return '';return 'backend/**'}
function proposalDetails(action){const p=action&&action.latestProposal&&action.latestProposal.summary;if(!p)return '';const changes=(p.changes||[]).map(c=>'<li><strong>'+esc(c.operation)+'</strong> '+esc(c.path)+'</li>').join('');const tests=(p.targetedTests||[]).map(v=>'<li>'+esc(v)+'</li>').join('');return '<div class="b8-proposal"><div class="decision-grid"><div><b>'+esc(L('Proposal hash','方案雜湊'))+'</b><span class="b8-hash">'+esc(p.proposalHash)+'</span></div><div><b>'+esc(L('Scope hash','範圍雜湊'))+'</b><span class="b8-hash">'+esc(p.scopeHash)+'</span></div><div><b>'+esc(L('Changes','修改檔案'))+'</b><span>'+esc((p.changes||[]).length)+'</span></div><div><b>'+esc(L('Beta.7 gate','Beta.7 Gate'))+'</b><span>'+esc(p.beta7Qa||L('Required but proposal omitted command','需要，但方案未提供命令'))+'</span></div></div><p>'+esc(p.summary||'')+'</p><div class="decision-grid"><div><b>'+esc(L('Exact reviewed changes','精確修改範圍'))+'</b><ul>'+changes+'</ul></div><div><b>'+esc(L('Targeted tests','目標測試'))+'</b><ul>'+tests+'</ul></div><div><b>'+esc(L('Regression','回歸測試'))+'</b><span>'+esc(p.regression||'—')+'</span></div><div><b>'+esc(L('Source content','程式碼內容'))+'</b><span>'+esc(L('Not exposed in dashboard summary','不在管理面板摘要暴露'))+'</span></div></div></div>'}
function acceptanceDetails(entry){if(!entry)return '';if(entry.record){const r=entry.record;return '<div class="b8-acceptance accepted"><div class="card-heading"><h2>'+esc(L('Locally accepted verified task','已在本機接受驗證任務'))+'</h2><span class="chip">'+esc(L('No push / no merge','未 Push / 未 Merge'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Commit','Commit'))+'</b><span class="b8-hash">'+esc(r.commitSha)+'</span></div><div><b>'+esc(L('Accepted by','接受者'))+'</b><span>'+esc(r.acceptedBy)+'</span></div><div><b>'+esc(L('Branch','分支'))+'</b><span>'+esc(r.branch)+'</span></div><div><b>'+esc(L('Verified files','已驗證檔案'))+'</b><span>'+esc((r.changedFiles||[]).length)+'</span></div></div></div>'}if(entry.preview){const p=entry.preview;return '<div class="b8-acceptance"><div class="card-heading"><h2>'+esc(L('Verified tree awaiting local acceptance','已驗證變更等待本機接受'))+'</h2><span class="chip">'+esc(L('Operator approval required','需要操作者核准'))+'</span></div><p>'+esc(L('Only these exact verified file hashes may enter the local acceptance commit. No repository hook, push or merge is run.','只有下列精確且已驗證的檔案雜湊可以進入本機接受 Commit；不執行 Repository Hook、Push 或 Merge。'))+'</p><ul>'+(p.changedFiles||[]).map(f=>'<li><strong>'+esc(f.operation)+'</strong> '+esc(f.path)+' <code>'+esc(f.sha256.slice(0,16))+'…</code></li>').join('')+'</ul><div class="b8-task-form"><label><span>'+esc(L('Accepted by','接受者'))+'</span><input data-b8-accept-by="'+esc(p.itemId)+'" value="owner" maxlength="120"></label><label><span>'+esc(L('Type acceptance hash suffix','輸入 Acceptance Hash 末 8 碼'))+' · <b>'+esc(p.acceptanceHash.slice(-8))+'</b></span><input data-b8-accept-confirm="'+esc(p.itemId)+'" maxlength="8" placeholder="'+esc(p.acceptanceHash.slice(-8))+'"></label><button class="primary-button" data-b8-task-action="accept" data-b8-item="'+esc(p.itemId)+'">'+esc(L('Create local acceptance commit','建立本機接受 Commit'))+'</button></div></div>'}return ''}
function taskCard(item,items,data){const action=item.action||{};const phase=action.phase||item.status;const ready=dependenciesReady(item,items);const acceptance=data.acceptance&&data.acceptance.items&&data.acceptance.items[item.id];let controls='';
  if(item.kind==='qa'){controls='<span class="chip">'+esc(L('Verification-only task; executed by the Beta.7 gate workflow','僅驗證任務；由 Beta.7 Gate 流程執行'))+'</span>'}
  else if(item.status==='planned'&&!item.approved){controls=ready?'<div class="b8-task-form"><label><span>'+esc(L('Approver','核准者'))+'</span><input data-b8-approver="'+esc(item.id)+'" value="owner" maxlength="120"></label><label><span>'+esc(L('Allowed repository paths','允許的 Repository 路徑'))+'</span><input data-b8-scope="'+esc(item.id)+'" value="'+esc(defaultScope(item))+'" placeholder="backend/**" maxlength="2000"></label><button class="primary-button" data-b8-task-action="approve" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Approve bounded scope','核准受控範圍'))+'</button></div>':'<span class="chip">'+esc(L('Waiting for dependencies','等待前置任務'))+'</span>'}
  else if(item.status==='approved'&&!action.latestProposal){controls=data.configuration.model?'<button class="primary-button" data-b8-task-action="propose" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Generate implementation proposal','產生實作方案'))+'</button>':'<span class="chip">'+esc(L('Configure Beta.8 model endpoint','請設定 Beta.8 模型端點'))+'</span>'}
  else if(item.status==='approved'&&action.latestProposal){const p=action.latestProposal.summary;const tail=p.proposalHash.slice(-8);controls='<div class="b8-task-form"><label><span>'+esc(L('Type proposal hash suffix to execute','輸入方案雜湊末 8 碼後執行'))+' · <b>'+esc(tail)+'</b></span><input data-b8-confirm="'+esc(item.id)+'" maxlength="8" placeholder="'+esc(tail)+'"></label><button class="primary-button" data-b8-task-action="execute" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Execute reviewed task','執行已審閱任務'))+'</button></div>'}
  else if(item.status==='completed'&&acceptance&&acceptance.record)controls='<span class="chip">'+esc(L('Accepted locally; clean tree can advance to the next task','已在本機接受；Clean Tree 可進入下一個任務'))+'</span>'
  else if(item.status==='completed'&&acceptance&&acceptance.preview)controls=''
  else if(item.status==='completed')controls='<button class="primary-button" data-b8-task-action="preview-acceptance" data-b8-item="'+esc(item.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Review verified tree for local acceptance','審閱已驗證變更並準備本機接受'))+'</button>'
  else controls='<span class="chip">'+esc(statusLabel(phase))+'</span>';
  return '<section class="panel b8-task"><div class="card-heading"><div><h2>'+esc(item.title)+'</h2><small>'+esc(item.id)+' · '+esc(item.kind)+' · '+esc(item.priority)+'</small></div><span class="status-pill '+esc(item.status)+'">'+esc(statusLabel(phase))+'</span></div><p>'+esc(action.message||'')+'</p><div class="decision-grid"><div><b>'+esc(L('Dependencies','依賴'))+'</b><span>'+esc((item.dependencies||[]).join(', ')||'—')+'</span></div><div><b>'+esc(L('Approved','已核准'))+'</b><span>'+esc(item.approved?L('Yes','是'):L('No','否'))+'</span></div><div><b>'+esc(L('Allowed paths','允許路徑'))+'</b><span>'+esc((item.allowedPaths||[]).join(', ')||'—')+'</span></div><div><b>'+esc(L('Attempt','嘗試'))+'</b><span>'+esc(action.latestAttempt?action.latestAttempt.outcome:'—')+'</span></div></div>'+proposalDetails(action)+acceptanceDetails(acceptance)+'<div class="pipeline-toolbar">'+controls+'</div></section>'}
function render(data){state=data;const page=document.querySelector('[data-page="beta8"]');if(!page)return;let host=document.getElementById('beta8LiveWorkflow');if(!host){host=document.createElement('div');host.id='beta8LiveWorkflow';page.appendChild(host)}
  if(data.error){host.innerHTML='<article id="beta8Error" class="panel">'+esc(data.error)+'</article>';return}
  if(data.phase==='not-started'){const can=data.configuration.repo&&data.actionsAllowed&&!pending;host.innerHTML='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend discovery','前端地毯式盤點'))+'</h2><small>'+esc(L('Read the existing frontend first. No backend code is generated in this step.','先完整讀取現有前端；此步驟不會產生後端程式碼。'))+'</small></div><span class="chip">Beta.8</span></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Discover" '+(can?'':'disabled')+'>'+esc(!data.configuration.repo?L('Configure repository first','請先設定 Repository'):!data.actionsAllowed?L('Read-only mode','唯讀模式'):L('Scan frontend','掃描前端'))+'</button></div></article>';const b=document.getElementById('b8Discover');if(b&&can)b.addEventListener('click',discover);return}
  const d=data.discovery||{};let html='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend inventory','前端盤點結果'))+'</h2><small>'+esc(d.projectName||'')+'</small></div><span class="chip">'+esc(data.phase)+'</span></div><div class="decision-grid"><div><b>'+esc(L('Files scanned','掃描檔案'))+'</b><span>'+esc(d.filesScanned||0)+'</span></div><div><b>'+esc(L('Routes / Forms','路由 / 表單'))+'</b><span>'+esc((d.routes||0)+' / '+(d.forms||0))+'</span></div><div><b>'+esc(L('API candidates','API 候選'))+'</b><span>'+esc(d.apiCandidates||0)+'</span></div><div><b>'+esc(L('Mock sources','Mock 來源'))+'</b><span>'+esc(d.mockSources||0)+'</span></div></div><p>'+esc(L('Frameworks: ','框架：'))+esc((d.frameworks||[]).join(', ')||'—')+'</p><p>'+esc(L('Entities: ','實體：'))+esc((d.entities||[]).join(', ')||'—')+'</p></article>';
  if(data.interview&&!data.blueprint){const answers=answerMap(data);const v=data.interview.validation||{};html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Architecture interview','後端架構訪談'))+'</h2><small>'+esc(L('Every required architecture decision must be explicitly confirmed before generation.','所有必要架構決策都必須明確確認後，才可開始生成。'))+'</small></div><span class="chip">'+esc(v.readyForBlueprint?L('Ready','可產生 Blueprint'):L('Blocked','尚未完成'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Missing','未回答'))+'</b><span>'+esc((v.missing||[]).length)+'</span></div><div><b>'+esc(L('Unconfirmed','未確認'))+'</b><span>'+esc((v.unconfirmed||[]).length)+'</span></div><div><b>'+esc(L('Invalid','無效'))+'</b><span>'+esc((v.invalid||[]).length)+'</span></div><div><b>'+esc(L('Unknown / duplicate','未知 / 重複'))+'</b><span>'+esc((v.unknownQuestionIds||[]).length+(v.duplicateQuestionIds||[]).length)+'</span></div></div></article>';
    for(const round of data.interview.rounds||[]){html+='<section class="b8-round"><div class="page-heading"><div><div class="eyebrow">'+esc(round.id)+'</div><h1>'+esc(roundTitle(round))+'</h1></div></div>'+round.questions.map(q=>questionCard(q,answers.get(q.id),data.actionsAllowed)).join('')+'</section>'}
    if(v.readyForBlueprint)html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Generate security-first blueprint','產生資安優先 Blueprint'))+'</h2><small>'+esc(L('This creates architecture, Work Plan and Mock Migration Plan artifacts. It still does not mutate product source code.','此動作會建立架構、Work Plan 與 Mock Migration Plan；仍不會修改產品程式碼。'))+'</small></div></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Blueprint" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Generate blueprint','產生 Blueprint'))+'</button></div></article>';
  }
  if(data.blueprint){const b=data.blueprint;html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Backend blueprint ready','後端 Blueprint 已完成'))+'</h2><small>'+esc(b.architecture.backendLanguage+' · '+b.architecture.backendFramework+' · '+b.architecture.database)+'</small></div><span class="chip">'+esc(b.workPlanValid?L('Work Plan valid','Work Plan 有效'):L('Work Plan blocked','Work Plan 受阻'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Security controls','資安控制'))+'</b><span>'+esc(b.securityControls)+'</span></div><div><b>'+esc(L('Threat surfaces','威脅面'))+'</b><span>'+esc(b.threatSurface)+'</span></div><div><b>'+esc(L('API / Entities','API / 實體'))+'</b><span>'+esc(b.apiEndpoints+' / '+b.entities)+'</span></div><div><b>'+esc(L('Tasks / Mocks','任務 / Mocks'))+'</b><span>'+esc(b.tasks+' / '+b.mockMigrationItems)+'</span></div></div></article><section class="b8-task-stack"><div class="page-heading"><div><div class="eyebrow">Beta.8 Implementation</div><h1>'+esc(L('Governed task execution','受控任務執行'))+'</h1><p>'+esc(L('Approve scope → generate proposal → review exact files/tests/hash → execute → accept the verified local tree before continuing.','核准範圍 → 產生方案 → 審閱精確檔案/測試/雜湊 → 執行 → 接受已驗證的本機變更後再繼續。'))+'</p></div></div>'+(b.workItems||[]).map(i=>taskCard(i,b.workItems,data)).join('')+'</section>'}
  host.innerHTML=html;host.querySelectorAll('[data-b8-save]').forEach(el=>el.addEventListener('click',()=>saveAnswer(el.getAttribute('data-b8-save'))));host.querySelectorAll('[data-b8-task-action]').forEach(el=>el.addEventListener('click',()=>taskAction(el.getAttribute('data-b8-task-action'),el.getAttribute('data-b8-item'))));const bp=document.getElementById('b8Blueprint');if(bp&&data.actionsAllowed)bp.addEventListener('click',generateBlueprint)
}
async function post(endpoint,payload){if(!state||!state.actionsAllowed)throw new Error(L('Dashboard is read-only.','管理面板目前為唯讀。'));const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body}
async function refresh(){try{const r=await fetch('/api/beta8',{headers:{accept:'application/json'},cache:'no-store'});render(await r.json())}catch(e){console.error('beta8 dashboard refresh failed',e)}}
async function discover(){if(pending)return;pending=true;try{render(state);await post('/api/beta8/discover',{});await refresh()}catch(e){showError(e)}finally{pending=false}}
function readQuestionValue(id,q){if(q.kind==='multi')return Array.from(document.querySelectorAll('[data-b8-multi="'+CSS.escape(id)+'"]:checked')).map(el=>el.value);const el=document.querySelector('[data-b8-input="'+CSS.escape(id)+'"]');if(!el)return '';if(q.kind==='boolean')return el.value==='true'?true:el.value==='false'?false:'';return el.value}
function showError(e){let host=document.getElementById('beta8Error');if(!host){host=document.createElement('div');host.id='beta8Error';host.className='panel';document.getElementById('beta8LiveWorkflow')?.prepend(host)}host.textContent=String(e&&e.message||e)}
async function saveAnswer(id){if(pending||!state||!state.interview)return;const q=(state.interview.rounds||[]).flatMap(r=>r.questions).find(x=>x.id===id);if(!q)return;const value=readQuestionValue(id,q);pending=true;try{await post('/api/beta8/answer',{questionId:id,value,confirmed:true});await refresh()}catch(e){showError(e)}finally{pending=false}}
async function generateBlueprint(){if(pending)return;pending=true;try{await post('/api/beta8/blueprint',{});await refresh()}catch(e){showError(e)}finally{pending=false}}
async function taskAction(action,itemId){if(pending||!itemId||!state||!state.blueprint)return;const item=state.blueprint.workItems.find(i=>i.id===itemId);if(!item)return;pending=true;try{
  if(action==='approve'){const who=document.querySelector('[data-b8-approver="'+CSS.escape(itemId)+'"]')?.value.trim();const raw=document.querySelector('[data-b8-scope="'+CSS.escape(itemId)+'"]')?.value||'';const allowedPaths=raw.split(/[\n,]+/).map(v=>v.trim()).filter(Boolean);await post('/api/beta8/approve-task',{itemId,approvedBy:who,allowedPaths})}
  else if(action==='propose')await post('/api/beta8/propose-task',{itemId});
  else if(action==='execute'){const p=item.action&&item.action.latestProposal&&item.action.latestProposal.summary;if(!p)throw new Error(L('No reviewed proposal is available.','沒有可審閱的方案。'));const typed=document.querySelector('[data-b8-confirm="'+CSS.escape(itemId)+'"]')?.value.trim();if(typed!==p.proposalHash.slice(-8))throw new Error(L('Proposal hash confirmation does not match; no files were changed.','方案雜湊確認碼不符，未修改任何檔案。'));await post('/api/beta8/execute-task',{itemId,proposalHash:p.proposalHash,confirmWrite:true})}
  else if(action==='preview-acceptance')await post('/api/beta8/preview-acceptance',{itemId});
  else if(action==='accept'){const entry=state.acceptance&&state.acceptance.items&&state.acceptance.items[itemId];const preview=entry&&entry.preview;if(!preview)throw new Error(L('No verified acceptance preview is available.','目前沒有可用的已驗證 Acceptance Preview。'));const who=document.querySelector('[data-b8-accept-by="'+CSS.escape(itemId)+'"]')?.value.trim();const typed=document.querySelector('[data-b8-accept-confirm="'+CSS.escape(itemId)+'"]')?.value.trim();if(typed!==preview.acceptanceHash.slice(-8))throw new Error(L('Acceptance hash confirmation does not match; no commit was created.','Acceptance Hash 確認碼不符，未建立 Commit。'));await post('/api/beta8/accept-task',{itemId,acceptanceHash:preview.acceptanceHash,acceptedBy:who})}
  await refresh();
}catch(e){showError(e)}finally{pending=false}}
function rerender(){if(state)render(state)}
function start(){refresh();setInterval(refresh,7000);new MutationObserver(rerender).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();`;
}
