export function beta8DashboardJs(): string {
  return `(()=>{
'use strict';
let state=null,pending=false;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function zh(){return (document.documentElement.lang||'').toLowerCase()==='zh-tw'}
function L(en,tc){return zh()?tc:en}
function answerMap(data){return new Map((((data||{}).interview||{}).answers||[]).map(a=>[a.questionId,a]))}
function valueControl(q,a){const name='b8-'+q.id;const value=a?a.value:null;
  if(q.kind==='boolean')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option><option value="true" '+(value===true?'selected':'')+'>'+esc(L('Yes','是'))+'</option><option value="false" '+(value===false?'selected':'')+'>'+esc(L('No','否'))+'</option></select>';
  if(q.kind==='single')return '<select data-b8-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option>'+((q.options||[]).map(o=>'<option value="'+esc(o)+'" '+(value===o?'selected':'')+'>'+esc(o)+'</option>').join(''))+'</select>';
  if(q.kind==='multi'){const selected=new Set(Array.isArray(value)?value:[]);return '<div class="b8-choice-grid">'+(q.options||[]).map(o=>'<label><input type="checkbox" data-b8-multi="'+esc(q.id)+'" value="'+esc(o)+'" '+(selected.has(o)?'checked':'')+'><span>'+esc(o)+'</span></label>').join('')+'</div>'}
  return '<textarea data-b8-input="'+esc(q.id)+'" rows="3" placeholder="'+esc(L('Enter details','輸入內容'))+'">'+esc(typeof value==='string'?value:'')+'</textarea>';
}
function questionCard(q,a){const suggested=(q.suggested||[]).length?'<small>'+esc(L('Suggested: ','建議：'))+esc(q.suggested.join(', '))+'</small>':'';const badge=q.requiresExplicitConfirmation?'<span class="chip">'+esc(L('Explicit confirmation','需明確確認'))+'</span>':'';return '<article class="panel b8-question" data-b8-question="'+esc(q.id)+'"><div class="card-heading"><div><h2>'+esc(q.prompt)+'</h2><small>'+esc(q.rationale)+'</small></div>'+badge+'</div>'+suggested+'<div class="b8-answer">'+valueControl(q,a)+'</div><div class="pipeline-toolbar"><span class="chip">'+esc(a&&a.confirmed?L('Confirmed','已確認'):L('Not confirmed','未確認'))+'</span><button class="primary-button" data-b8-save="'+esc(q.id)+'">'+esc(L('Save & confirm','儲存並確認'))+'</button></div></article>'}
function render(data){state=data;const page=document.querySelector('[data-page="beta8"]');if(!page)return;let host=document.getElementById('beta8LiveWorkflow');if(!host){host=document.createElement('div');host.id='beta8LiveWorkflow';page.appendChild(host)}
  if(data.phase==='not-started'){host.innerHTML='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend discovery','前端地毯式盤點'))+'</h2><small>'+esc(L('Read the existing frontend first. No backend code is generated in this step.','先完整讀取現有前端；此步驟不會產生後端程式碼。'))+'</small></div><span class="chip">Beta.8</span></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Discover" '+(!data.configuration.repo||pending?'disabled':'')+'>'+esc(data.configuration.repo?L('Scan frontend','掃描前端'):L('Configure repository first','請先設定 Repository'))+'</button></div></article>';const b=document.getElementById('b8Discover');if(b)b.addEventListener('click',discover);return}
  const d=data.discovery||{};let html='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Frontend inventory','前端盤點結果'))+'</h2><small>'+esc(d.projectName||'')+'</small></div><span class="chip">'+esc(data.phase)+'</span></div><div class="decision-grid"><div><b>'+esc(L('Files scanned','掃描檔案'))+'</b><span>'+esc(d.filesScanned||0)+'</span></div><div><b>'+esc(L('Routes / Forms','路由 / 表單'))+'</b><span>'+esc((d.routes||0)+' / '+(d.forms||0))+'</span></div><div><b>'+esc(L('API candidates','API 候選'))+'</b><span>'+esc(d.apiCandidates||0)+'</span></div><div><b>'+esc(L('Mock sources','Mock 來源'))+'</b><span>'+esc(d.mockSources||0)+'</span></div></div><p>'+esc(L('Frameworks: ','框架：'))+esc((d.frameworks||[]).join(', ')||'—')+'</p><p>'+esc(L('Entities: ','實體：'))+esc((d.entities||[]).join(', ')||'—')+'</p></article>';
  if(data.interview){const answers=answerMap(data);const v=data.interview.validation||{};html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Architecture interview','後端架構訪談'))+'</h2><small>'+esc(L('Every required architecture decision must be explicitly confirmed before generation.','所有必要架構決策都必須明確確認後，才可開始生成。'))+'</small></div><span class="chip">'+esc(v.readyForBlueprint?L('Ready','可產生 Blueprint'):L('Blocked','尚未完成'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Missing','未回答'))+'</b><span>'+esc((v.missing||[]).length)+'</span></div><div><b>'+esc(L('Unconfirmed','未確認'))+'</b><span>'+esc((v.unconfirmed||[]).length)+'</span></div><div><b>'+esc(L('Invalid','無效'))+'</b><span>'+esc((v.invalid||[]).length)+'</span></div><div><b>'+esc(L('Unknown / duplicate','未知 / 重複'))+'</b><span>'+esc((v.unknownQuestionIds||[]).length+(v.duplicateQuestionIds||[]).length)+'</span></div></div></article>';
    for(const round of data.interview.rounds||[]){html+='<section class="b8-round"><div class="page-heading"><div><div class="eyebrow">'+esc(round.id)+'</div><h1>'+esc(round.title)+'</h1></div></div>'+round.questions.map(q=>questionCard(q,answers.get(q.id))).join('')+'</section>'}
    if(v.readyForBlueprint&&!data.blueprint)html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Generate security-first blueprint','產生資安優先 Blueprint'))+'</h2><small>'+esc(L('This creates immutable architecture, Work Plan and Mock Migration Plan artifacts. It still does not mutate product source code.','此動作會建立不可覆寫的架構、Work Plan 與 Mock Migration Plan；仍不會修改產品程式碼。'))+'</small></div></div><div class="pipeline-toolbar"><button class="primary-button" id="b8Blueprint" '+(pending?'disabled':'')+'>'+esc(L('Generate blueprint','產生 Blueprint'))+'</button></div></article>';
  }
  if(data.blueprint){const b=data.blueprint;html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Backend blueprint ready','後端 Blueprint 已完成'))+'</h2><small>'+esc(b.architecture.backendLanguage+' · '+b.architecture.backendFramework+' · '+b.architecture.database)+'</small></div><span class="chip">'+esc(b.workPlanValid?L('Work Plan valid','Work Plan 有效'):L('Work Plan blocked','Work Plan 受阻'))+'</span></div><div class="decision-grid"><div><b>'+esc(L('Security controls','資安控制'))+'</b><span>'+esc(b.securityControls)+'</span></div><div><b>'+esc(L('Threat surfaces','威脅面'))+'</b><span>'+esc(b.threatSurface)+'</span></div><div><b>'+esc(L('API / Entities','API / 實體'))+'</b><span>'+esc(b.apiEndpoints+' / '+b.entities)+'</span></div><div><b>'+esc(L('Tasks / Mocks','任務 / Mocks'))+'</b><span>'+esc(b.tasks+' / '+b.mockMigrationItems)+'</span></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>'+esc(L('Task','任務'))+'</th><th>'+esc(L('Kind','類型'))+'</th><th>'+esc(L('Priority','優先級'))+'</th><th>'+esc(L('Dependencies','依賴'))+'</th><th>'+esc(L('Status','狀態'))+'</th></tr></thead><tbody>'+(b.workItems||[]).map(i=>'<tr><td><strong>'+esc(i.id)+'</strong></td><td>'+esc(i.title)+'</td><td>'+esc(i.kind)+'</td><td>'+esc(i.priority)+'</td><td>'+esc((i.dependencies||[]).join(', ')||'—')+'</td><td><span class="status-pill '+esc(i.status)+'">'+esc(i.status)+'</span></td></tr>').join('')+'</tbody></table></div><p class="empty-state">'+esc(L('Execution remains approval-blocked. The next stage approves and executes one bounded task at a time, then runs Beta.7.','執行仍被核准機制阻擋。下一階段會逐項核准並執行受控任務，之後執行 Beta.7。'))+'</p></article>'}
  host.innerHTML=html;host.querySelectorAll('[data-b8-save]').forEach(el=>el.addEventListener('click',()=>saveAnswer(el.getAttribute('data-b8-save'))));const bp=document.getElementById('b8Blueprint');if(bp)bp.addEventListener('click',generateBlueprint)
}
async function post(endpoint,payload){const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body}
async function refresh(){try{const r=await fetch('/api/beta8',{headers:{accept:'application/json'},cache:'no-store'});render(await r.json())}catch(e){console.error('beta8 dashboard refresh failed',e)}}
async function discover(){if(pending)return;pending=true;try{render(state);render(await post('/api/beta8/discover',{}))}catch(e){console.error(e);alertFallback(e)}finally{pending=false}}
function readQuestionValue(id,q){if(q.kind==='multi')return Array.from(document.querySelectorAll('[data-b8-multi="'+CSS.escape(id)+'"]:checked')).map(el=>el.value);const el=document.querySelector('[data-b8-input="'+CSS.escape(id)+'"]');if(!el)return '';if(q.kind==='boolean')return el.value==='true'?true:el.value==='false'?false:'';return el.value}
function alertFallback(e){let host=document.getElementById('beta8Error');if(!host){host=document.createElement('div');host.id='beta8Error';host.className='panel';document.getElementById('beta8LiveWorkflow')?.prepend(host)}host.textContent=String(e&&e.message||e)}
async function saveAnswer(id){if(pending||!state||!state.interview)return;const q=(state.interview.rounds||[]).flatMap(r=>r.questions).find(x=>x.id===id);if(!q)return;const value=readQuestionValue(id,q);pending=true;try{render(await post('/api/beta8/answer',{questionId:id,value,confirmed:true}))}catch(e){alertFallback(e)}finally{pending=false}}
async function generateBlueprint(){if(pending)return;pending=true;try{render(await post('/api/beta8/blueprint',{}))}catch(e){alertFallback(e)}finally{pending=false}}
function rerender(){if(state)render(state)}
function start(){refresh();setInterval(refresh,7000);new MutationObserver(rerender).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();`;
}
