export function beta8QaDashboardJs(): string {
  return `(()=>{
'use strict';
let snapshot=null,pending=false;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function zh(){return (document.documentElement.lang||'').toLowerCase()==='zh-tw'}
function L(en,tc){return zh()?tc:en}
function post(endpoint,payload){return fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body})}
function errorBox(error){let host=document.getElementById('beta8QaError');if(!host){host=document.createElement('article');host.id='beta8QaError';host.className='panel b8q-error';document.getElementById('beta8QaWorkflow')?.prepend(host)}host.textContent=String(error&&error.message||error)}
function severity(v){return '<span class="status-pill '+esc(v)+'">'+esc(v||'—')+'</span>'}
function findingRows(data){const source=data.finalQa&&data.finalQa.findings;if(!source||!source.available||!source.findings)return '';return source.findings.map(f=>'<tr><td><input type="checkbox" data-b8q-finding value="'+esc(f.fingerprint)+'" '+(f.selected?'checked disabled':'')+' aria-label="'+esc(f.title)+'"></td><td>'+severity(f.severity)+'</td><td><strong>'+esc(f.title)+'</strong><small>'+esc(f.kind)+' · '+esc(f.url)+'</small></td><td><code>'+esc(f.fingerprint.slice(0,18))+'…</code></td></tr>').join('')}
function render(data){snapshot=data;const page=document.querySelector('[data-page="beta8"]');if(!page)return;let host=document.getElementById('beta8QaWorkflow');if(!host){host=document.createElement('section');host.id='beta8QaWorkflow';page.appendChild(host)}const q=data.finalQa;if(!q){host.innerHTML='';return}let html='<div class="page-heading b8q-heading"><div><div class="eyebrow">Beta.8 → Beta.7 → Beta.9</div><h1>'+esc(L('Final QA & findings handoff','最終 QA 與 Findings 交接'))+'</h1><p>'+esc(L('Run one bounded Beta.7 gate after backend/mock work is complete. Exactly one new result is accepted; ambiguous results are blocked rather than guessed.','後端與 Mock 工作完成後執行一次受控 Beta.7 Gate。只接受唯一的新結果；多份候選會阻擋而不是猜測。'))+'</p></div></div>';
  if(!q.available){html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Final Beta.7 QA','最終 Beta.7 QA'))+'</h2><small>'+esc(q.readyToRun?L('All prerequisite work is complete.','所有前置工作已完成。'):L('Prerequisites are not complete.','前置工作尚未完成。'))+'</small></div><span class="chip">'+esc(q.readyToRun?L('Ready','可執行'):L('Blocked','受阻'))+'</span></div>'+(q.blockers&&q.blockers.length?'<ul class="b8q-blockers">'+q.blockers.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul>':'')+'<div class="b8q-command"><label><span>'+esc(L('Program','程式'))+'</span><input id="b8qProgram" value="npm"></label><label><span>'+esc(L('Arguments','參數'))+'</span><input id="b8qArgs" value="run qa"></label><button class="primary-button" id="b8qRun" '+(!data.actionsAllowed||!q.readyToRun||pending?'disabled':'')+'>'+esc(L('Run final Beta.7 QA','執行最終 Beta.7 QA'))+'</button></div></article>';host.innerHTML=html;document.getElementById('b8qRun')?.addEventListener('click',runQa);return}
  const qa=q.qa||{};const counts=qa.counts||{};html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Final QA result','最終 QA 結果'))+'</h2><small>'+esc(qa.runId||'')+' · '+esc(qa.result||'')+'</small></div><span class="status-pill '+(Number(qa.blockingFindings||0)>0?'high':'completed')+'">'+esc(Number(qa.blockingFindings||0)>0?L('Needs review','需要處理'):L('No High/Critical blockers','無 High/Critical 阻擋'))+'</span></div><div class="decision-grid"><div><b>Critical</b><span>'+esc(counts.critical||0)+'</span></div><div><b>High</b><span>'+esc(counts.high||0)+'</span></div><div><b>Medium</b><span>'+esc(counts.medium||0)+'</span></div><div><b>Low / Info</b><span>'+esc(Number(counts.low||0)+Number(counts.info||0))+'</span></div></div><p>'+esc(L('Command: ','命令：'))+'<code>'+esc(qa.command||'')+'</code></p>'+(qa.report?'<div class="b8q-report"><strong>'+esc(L('Evidence report','證據報告'))+'</strong><span>'+esc(qa.report.html||qa.report.markdown||L('Report metadata available','已有報告 metadata'))+'</span><span>'+esc(L('Videos: ','影片：'))+esc(qa.report.videos||0)+'</span></div>':'')+'</article>';
  const rows=findingRows(data);if(rows){html+='<article class="panel"><div class="card-heading"><div><h2>'+esc(L('Findings ready for Beta.9','可交給 Beta.9 的 Findings'))+'</h2><small>'+esc(L('Select only findings you want the repair planner to receive. Creating a Beta.9 plan still does not grant source mutation.','只勾選要交給修復規劃器的問題；建立 Beta.9 Plan 仍不代表授權修改程式碼。'))+'</small></div><span class="chip">'+esc((q.findings&&q.findings.total)||0)+' '+esc(L('findings','問題'))+'</span></div><div class="table-wrap"><table><thead><tr><th></th><th>'+esc(L('Severity','嚴重度'))+'</th><th>'+esc(L('Finding','問題'))+'</th><th>Fingerprint</th></tr></thead><tbody>'+rows+'</tbody></table></div><div class="pipeline-toolbar"><button class="primary-button" id="b8qHandoff" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Create Beta.9 plan from selection','從選取項目建立 Beta.9 Plan'))+'</button></div></article>'}
  host.innerHTML=html;document.getElementById('b8qHandoff')?.addEventListener('click',handoff)}
async function refresh(){try{const r=await fetch('/api/beta8',{headers:{accept:'application/json'},cache:'no-store'});render(await r.json())}catch(e){console.error('beta8 final qa refresh failed',e)}}
async function runQa(){if(pending)return;const program=document.getElementById('b8qProgram')?.value.trim()||'';const args=(document.getElementById('b8qArgs')?.value||'').trim().split(/\s+/).filter(Boolean);pending=true;try{await post('/api/beta8/run-final-qa',{command:{program,args}});await refresh()}catch(e){errorBox(e)}finally{pending=false}}
async function handoff(){if(pending)return;const fingerprints=Array.from(document.querySelectorAll('[data-b8q-finding]:checked:not(:disabled)')).map(el=>el.value);if(!fingerprints.length){errorBox(new Error(L('Select at least one finding.','請至少選擇一個 Finding。')));return}pending=true;try{await post('/api/beta8/send-findings-beta9',{fingerprints,project:'Beta.8 final QA handoff'});await refresh()}catch(e){errorBox(e)}finally{pending=false}}
function rerender(){if(snapshot)render(snapshot)}
function start(){refresh();setInterval(refresh,7000);new MutationObserver(rerender).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();`;
}
