export function featurePlannerDashboardJs(): string {
  return `(()=>{
'use strict';
let snapshot=null,pending=false;
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function zh(){return (document.documentElement.lang||'').toLowerCase()==='zh-tw'}
function L(en,tc){return zh()?tc:en}
function lines(v){return String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function post(endpoint,payload){return fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload)}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b})}
function errorBox(error){const host=document.getElementById('featurePlannerError');if(!host)return;host.hidden=false;host.textContent=String(error&&error.message||error)}
function clearError(){const host=document.getElementById('featurePlannerError');if(host){host.hidden=true;host.textContent=''}}
function activate(){document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('is-active',el.getAttribute('data-page')==='features'));document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('is-active',el.getAttribute('data-route')==='features'));}
function installShell(){
  const side=document.querySelector('.side-nav');if(side&&!side.querySelector('[data-route="features"]')){const b=document.createElement('button');b.className='nav-button';b.setAttribute('data-route','features');b.setAttribute('aria-label','Feature Planner');b.innerHTML='<span>＋</span><b>'+esc(L('Features','功能規劃'))+'</b>';b.addEventListener('click',activate);side.appendChild(b)}
  const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('[data-route="features"]')){mobile.classList.add('feature-nav-enabled');const b=document.createElement('button');b.setAttribute('data-route','features');b.innerHTML='＋<span>'+esc(L('Features','功能'))+'</span>';b.addEventListener('click',activate);mobile.appendChild(b)}
  const main=document.querySelector('.main-shell');if(main&&!document.getElementById('featurePlannerPage')){const page=document.createElement('section');page.id='featurePlannerPage';page.className='page';page.setAttribute('data-page','features');page.innerHTML='<div class="page-heading"><div><div class="eyebrow">Product Planning</div><h1>'+esc(L('Product / Feature Planner','產品／功能規劃器'))+'</h1><p>'+esc(L('Turn a product request into an explicit, reviewable implementation contract before any source mutation is allowed.','先把產品需求整理成可審閱、可確認的實作契約；在此階段不允許修改產品原始碼。'))+'</p></div><span class="chip">'+esc(L('Planning only · mutation disabled','僅規劃 · 禁止修改原始碼'))+'</span></div><article id="featurePlannerError" class="panel fp-error" hidden></article><div id="featurePlannerBody"></div>';main.appendChild(page)}
}
function label(text,control){return '<label class="fp-field"><span>'+esc(text)+'</span>'+control+'</label>'}
function emptyView(data){const disabled=!data.actionsAllowed||pending?'disabled':'';return '<article class="panel fp-hero"><div><div class="eyebrow">01 · '+esc(L('Opportunity','需求機會'))+'</div><h2>'+esc(L('Describe what should improve','描述希望改善的產品結果'))+'</h2><p>'+esc(L('This creates a planning session only. It does not generate or edit product source code.','這只會建立規劃工作階段，不會生成或修改產品原始碼。'))+'</p></div><span class="chip">'+esc(data.actionsAllowed?L('Actions enabled','可操作'):L('Read-only mode','唯讀模式'))+'</span></article><article class="panel"><div class="fp-grid">'+
label(L('Project','專案'),'<input id="fpProject" maxlength="200" placeholder="my-product">')+
label(L('Feature title','功能名稱'),'<input id="fpTitle" maxlength="300" placeholder="'+esc(L('Guided approval review','引導式核准審閱'))+'">')+
label(L('Expected impact','預期影響'),'<select id="fpImpact"><option value="high">'+esc(L('High','高'))+'</option><option value="medium" selected>'+esc(L('Medium','中'))+'</option><option value="low">'+esc(L('Low','低'))+'</option></select>')+
label(L('Estimated effort','預估工作量'),'<select id="fpEffort"><option value="low">'+esc(L('Low','低'))+'</option><option value="medium" selected>'+esc(L('Medium','中'))+'</option><option value="high">'+esc(L('High','高'))+'</option></select>')+
'</div>'+label(L('Current problem / observation','目前問題／觀察'),'<textarea id="fpObservation" rows="3"></textarea>')+label(L('User value / desired outcome','使用者價值／期望結果'),'<textarea id="fpUserValue" rows="3"></textarea>')+
'<div class="fp-grid">'+label(L('Affected areas · one per line','影響範圍 · 每行一項'),'<textarea id="fpAreas" rows="4" placeholder="dashboard\nplanning"></textarea>')+label(L('Design-system constraints · one per line','設計系統限制 · 每行一項'),'<textarea id="fpDesign" rows="4"></textarea>')+'</div>'+label(L('Current product understanding · one per line','目前產品理解 · 每行一項'),'<textarea id="fpUnderstanding" rows="4"></textarea>')+'<div class="fp-actions"><button class="primary-button" id="fpStart" '+disabled+'>'+esc(L('Start planning','開始規劃'))+'</button></div></article>'}
const QZH={
'feature-goal-confirmation':['確認這個功能必須改善的使用者結果。','避免實作方向最佳化了使用者沒有要求的目標。'],
'target-users':['哪些使用者應該可以使用這個功能？','這會界定產品範圍、權限與 QA Persona。'],
'must-preserve-existing-flow':['上線期間是否必須保留目前既有流程？','這會影響遷移、Feature Flag 與相容策略。'],
'design-system-boundary':['除非明確核准重新設計，是否必須沿用目前產品設計系統？','避免生成的功能自行發明一套無關的視覺語言。'],
'data-sensitivity':['新功能會處理哪些資料敏感等級？','決定儲存、日誌、授權與保存要求。'],
'release-strategy':['選擇發佈策略。','這會決定風險控制與 Beta.7 的驗證方式。']};
const OZH={'All users':'所有使用者','Authenticated users':'已登入使用者','Admin/owner only':'管理員／擁有者','Role-based subset':'指定角色','Other':'其他','Public':'公開資料','Internal':'內部資料','Personal data':'個人資料','Sensitive personal data':'敏感個資','Credentials/tokens':'憑證／Token','Payment/financial':'付款／金融','None':'無','Feature flag / staged rollout':'Feature Flag／分階段發佈','Owner-only preview':'僅擁有者預覽','All users after QA':'QA 後全量開放'};
function qPrompt(q,key){const pair=QZH[q.id];if(zh()&&pair)return pair[key];return key===0?q.prompt:q.reason}
function opt(v){return zh()?(OZH[v]||v):v}
function control(q,a){const value=a?a.value:null;if(q.kind==='boolean')return '<select data-fp-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option><option value="true" '+(value===true?'selected':'')+'>'+esc(L('Yes','是'))+'</option><option value="false" '+(value===false?'selected':'')+'>'+esc(L('No','否'))+'</option></select>';if(q.kind==='single')return '<select data-fp-input="'+esc(q.id)+'"><option value="">'+esc(L('Choose…','請選擇…'))+'</option>'+(q.options||[]).map(o=>'<option value="'+esc(o)+'" '+(value===o?'selected':'')+'>'+esc(opt(o))+'</option>').join('')+'</select>';if(q.kind==='multi'){const selected=new Set(Array.isArray(value)?value:[]);return '<div class="fp-choices">'+(q.options||[]).map(o=>'<label><input type="checkbox" data-fp-multi="'+esc(q.id)+'" value="'+esc(o)+'" '+(selected.has(o)?'checked':'')+'><span>'+esc(opt(o))+'</span></label>').join('')+'</div>'}return '<textarea data-fp-input="'+esc(q.id)+'" rows="3">'+esc(typeof value==='string'?value:'')+'</textarea>'}
function interviewView(data){const answers=new Map((data.answers||[]).map(a=>[a.questionId,a]));const missing=data.validation&&data.validation.missing||[];return '<article class="panel fp-hero"><div><div class="eyebrow">02 · '+esc(L('Decision interview','決策訪談'))+'</div><h2>'+esc(data.session.opportunity.title)+'</h2><p>'+esc(L('Every required product decision must be explicitly confirmed before a blueprint can be frozen.','所有必要產品決策都必須明確確認，才能凍結功能藍圖。'))+'</p></div><span class="chip">'+esc(missing.length)+' '+esc(L('unresolved','項未完成'))+'</span></article><div class="fp-stack">'+data.session.questions.map(q=>{const a=answers.get(q.id);return '<article class="panel fp-question"><div class="card-heading"><div><h2>'+esc(qPrompt(q,0))+'</h2><small>'+esc(qPrompt(q,1))+'</small></div><span class="chip">'+esc(a&&a.confirmed?L('Confirmed','已確認'):L('Required','必填'))+'</span></div><div class="fp-answer">'+control(q,a)+'</div><div class="fp-actions"><button class="primary-button" data-fp-save="'+esc(q.id)+'" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Save & confirm','儲存並確認'))+'</button></div></article>'}).join('')+'</div>'}
function alternativeCard(a){return '<label class="fp-alt"><input type="radio" name="fpAlternative" value="'+esc(a.id)+'" '+(a.id==='balanced'?'checked':'')+'><div><strong>'+esc(a.title)+'</strong><p>'+esc(a.summary)+'</p><small>'+esc(L('Cost: ','成本：'))+esc(a.implementationCost)+'</small></div></label>'}
function blueprintForm(data){return '<article class="panel fp-hero"><div><div class="eyebrow">03 · '+esc(L('Blueprint','功能藍圖'))+'</div><h2>'+esc(L('Freeze the product contract','凍結產品契約'))+'</h2><p>'+esc(L('Choose the intended product shape, then state the exact frontend/backend/data/security requirements.','選擇產品方案，並明確填入前端、後端、資料與資安要求。'))+'</p></div><span class="chip">'+esc(L('All decisions confirmed','所有決策已確認'))+'</span></article><article class="panel"><h2>'+esc(L('Implementation alternative','實作方案'))+'</h2><div class="fp-alternatives">'+data.session.alternatives.map(alternativeCard).join('')+'</div><div class="fp-grid">'+label(L('User flow · one step per line','使用流程 · 每行一步'),'<textarea id="fpUserFlow" rows="6"></textarea>')+label(L('Information architecture · one per line','資訊架構 · 每行一項'),'<textarea id="fpIA" rows="6"></textarea>')+label(L('Frontend requirements','前端需求'),'<textarea id="fpFrontend" rows="6"></textarea>')+label(L('Backend requirements','後端需求'),'<textarea id="fpBackend" rows="6"></textarea>')+label(L('Data requirements','資料需求'),'<textarea id="fpData" rows="6"></textarea>')+label(L('Security requirements','資安需求'),'<textarea id="fpSecurity" rows="6"></textarea>')+'</div><div class="fp-warning">'+esc(L('Freezing creates an immutable planning artifact. It still does not approve or execute source changes.','凍結後會建立不可覆寫的規劃成果；此動作仍不代表核准或執行任何原始碼修改。'))+'</div><div class="fp-actions"><button class="primary-button" id="fpFreeze" '+(!data.actionsAllowed||pending?'disabled':'')+'>'+esc(L('Freeze blueprint','凍結藍圖'))+'</button></div></article>'}
function blueprintView(data){const b=data.blueprint;const rows=(b.workPlan.items||[]).map(i=>'<tr><td><strong>'+esc(i.id)+'</strong></td><td>'+esc(i.kind)+'</td><td>'+esc(i.title)+'</td><td>'+esc(i.priority)+'</td><td>'+esc(i.dependencies.join(', ')||'—')+'</td><td><span class="status-pill '+esc(i.status)+'">'+esc(i.status)+'</span></td><td>'+esc(i.execution.mutationAllowed?L('Enabled','已開放'):L('Disabled','禁止'))+'</td></tr>').join('');return '<article class="panel fp-hero"><div><div class="eyebrow">04 · '+esc(L('Frozen blueprint','已凍結藍圖'))+'</div><h2>'+esc(b.selectedAlternative.title)+'</h2><p>'+esc(b.selectedAlternative.summary)+'</p></div><span class="chip">'+esc(data.workPlanValid?L('Plan valid','計畫有效'):L('Plan invalid','計畫無效'))+'</span></article><article class="panel"><div class="decision-grid"><div><b>'+esc(L('Frontend','前端'))+'</b><span>'+esc(b.frontendRequirements.length)+'</span></div><div><b>'+esc(L('Backend','後端'))+'</b><span>'+esc(b.backendRequirements.length)+'</span></div><div><b>'+esc(L('Security','資安'))+'</b><span>'+esc(b.securityRequirements.length)+'</span></div><div><b>'+esc(L('Work items','工作項目'))+'</b><span>'+esc(b.workPlan.items.length)+'</span></div></div><div class="fp-warning safe">'+esc(L('Planning boundary preserved: every generated work item still has mutationAllowed=false and requires a separate approval/execution workflow.','規劃邊界仍完整保留：所有工作項目仍為 mutationAllowed=false，後續必須經獨立核准與執行流程。'))+'</div><div class="table-wrap"><table><thead><tr><th>ID</th><th>'+esc(L('Kind','類型'))+'</th><th>'+esc(L('Task','任務'))+'</th><th>'+esc(L('Priority','優先級'))+'</th><th>'+esc(L('Dependencies','依賴'))+'</th><th>'+esc(L('Status','狀態'))+'</th><th>'+esc(L('Mutation','原始碼修改'))+'</th></tr></thead><tbody>'+rows+'</tbody></table></div></article>'}
function render(data){snapshot=data;installShell();const body=document.getElementById('featurePlannerBody');if(!body)return;if(data.error){body.innerHTML='<article class="panel fp-error">'+esc(data.error)+'</article>';return}if(data.phase==='empty')body.innerHTML=emptyView(data);else if(data.phase==='interview')body.innerHTML=interviewView(data);else if(data.phase==='ready-for-blueprint')body.innerHTML=blueprintForm(data);else body.innerHTML=blueprintView(data);bind()}
function valueFor(id){const single=document.querySelector('[data-fp-input="'+CSS.escape(id)+'"]');if(single){if(single.tagName==='SELECT'&&single.value==='true')return true;if(single.tagName==='SELECT'&&single.value==='false')return false;return single.value}return Array.from(document.querySelectorAll('[data-fp-multi="'+CSS.escape(id)+'"]:checked')).map(el=>el.value)}
function bind(){document.getElementById('fpStart')?.addEventListener('click',create);document.querySelectorAll('[data-fp-save]').forEach(el=>el.addEventListener('click',()=>save(el.getAttribute('data-fp-save'))));document.getElementById('fpFreeze')?.addEventListener('click',freeze)}
async function create(){if(pending)return;pending=true;clearError();try{const next=await post('/api/features/create',{project:document.getElementById('fpProject').value,title:document.getElementById('fpTitle').value,observation:document.getElementById('fpObservation').value,userValue:document.getElementById('fpUserValue').value,expectedImpact:document.getElementById('fpImpact').value,estimatedEffort:document.getElementById('fpEffort').value,affectedAreas:lines(document.getElementById('fpAreas').value),designSystemConstraints:lines(document.getElementById('fpDesign').value),currentProductUnderstanding:lines(document.getElementById('fpUnderstanding').value)});render(next)}catch(e){errorBox(e)}finally{pending=false}}
async function save(id){if(pending||!id)return;pending=true;clearError();try{render(await post('/api/features/answer',{questionId:id,value:valueFor(id),confirmed:true}))}catch(e){errorBox(e)}finally{pending=false}}
async function freeze(){if(pending)return;pending=true;clearError();try{const selected=document.querySelector('input[name="fpAlternative"]:checked');render(await post('/api/features/blueprint',{selectedAlternativeId:selected?selected.value:'',userFlow:lines(document.getElementById('fpUserFlow').value),informationArchitecture:lines(document.getElementById('fpIA').value),frontendRequirements:lines(document.getElementById('fpFrontend').value),backendRequirements:lines(document.getElementById('fpBackend').value),dataRequirements:lines(document.getElementById('fpData').value),securityRequirements:lines(document.getElementById('fpSecurity').value)}))}catch(e){errorBox(e)}finally{pending=false}}
async function refresh(){try{const r=await fetch('/api/features',{headers:{accept:'application/json'},cache:'no-store'});render(await r.json())}catch(e){console.error('feature planner refresh failed',e)}}
function rerender(){if(snapshot)render(snapshot)}
function start(){installShell();refresh();new MutationObserver(rerender).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();`;
}
